fix: the iso C++17 does not support dynamic except
```
error: ISO C++17 does not allow dynamic exception specifications
 1587 | ree(string path, string suffix, bool overwrite=true) const throw (Exception)
      |
```